resources:
  - name: dwpdigital-docker-aviator
    type: registry-image-resource
    source:
      repository: dwpdigital/docker-aviator
    check_every: 5m

  - name: ecr-dwpdigital-docker-aviator-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "docker-aviator"

  - name: ecr-dwpdigital-docker-aviator
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "docker-aviator"
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci

jobs:
  - name: mirror-dwpdigital-docker-aviator-dev
    serial_groups: [docker-aviator]
    plan:
      - get: dwpdigital-docker-aviator
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-docker-aviator-dev
        params:
          image: "dwpdigital-docker-aviator/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-docker-aviator
    serial_groups: [docker-aviator]
    plan:
      - get: dwpdigital-docker-aviator
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-docker-aviator
        params:
          image: "dwpdigital-docker-aviator/image.tar"
        attempts: 3
